version: '3'

services:
  pseudo_app:
    container_name: pseudo_app
    restart: always
    build: ./pseudo_app
    ports:
      - "8000:8000"
    command: gunicorn -w 3 --timeout 90 -b 0.0.0.0:8000 wsgi:server

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - pseudo_app
